apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: JujuCluster
metadata:
  labels:
    app.kubernetes.io/name: jujucluster
    app.kubernetes.io/instance: jujucluster-sample
    app.kubernetes.io/part-of: cluster-api-provider-juju
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-provider-juju
  name: jujucluster-sample
spec:
  # using loadbalancer requires metallb on vsphere
  model:
    name: jujucluster-sample
    cloud: jujucluster-sample 
    cloudRegion: Boston
    credentialName: jujucluster-sample
    config: 
      juju-http-proxy: "http://squid.internal:3128"
      apt-http-proxy: "http://squid.internal:3128"
      snap-http-proxy: "http://squid.internal:3128"
      juju-https-proxy: "http://squid.internal:3128"
      apt-https-proxy: "http://squid.internal:3128"
      snap-https-proxy: "http://squid.internal:3128"
      apt-no-proxy: "localhost,127.0.0.1,ppa.launchpad.net,launchpad.net"
      juju-no-proxy: "localhost,127.0.0.1,0.0.0.0,ppa.launchpad.net,launchpad.net,10.0.8.0/24,10.246.154.0/24"
      logging-config: "<root>=DEBUG"
      datastore: "vsanDatastore"
      primary-network: "VLAN_2764"
      force-vm-hardware-version: "17"
    constraints:
      arch: amd64
  controllerServiceType: loadbalancer
  credential:
    credentialSecretName: jujucluster-sample-credential-secret
    credentialSecretNamespace: default
  cloud:
    name: jujucluster-sample
    type: vsphere
    endpoint: 10.246.152.100
    regions:
      - name: Boston
        endpoint: 10.246.152.100
    authTypes:
      - "userpass"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster-sample
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: JujuCluster
    name: jujucluster-sample
