apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: JujuMachine
metadata:
  labels:
    app.kubernetes.io/name: jujumachine
    app.kubernetes.io/instance: jujumachine-sample
    app.kubernetes.io/part-of: cluster-api-provider-juju
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-provider-juju
  name: jujumachine-sample
spec:
  # TODO(user): Add fields here
  foo: bar
---
kind: Machine
apiVersion: cluster.x-k8s.io/v1beta1
metadata:
  name: jujumachine-sample
  labels:
    cluster.x-k8s.io/cluster-name: jujucluster-sample
    cluster.x-k8s.io/control-plane: "false"
spec:
  clusterName: jujucluster-sample
  bootstrap:
    dataSecretName: "asdf"
  infrastructureRef:
    kind: JujuMachine
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: jujumachine-sample
