# This is an example vsphere credential file
# see https://juju.is/docs/olm/add-credentials#heading--use-a-yaml-file for details regarding other clouds
credentials:
  jujucluster-sample: # cloud name
    jujucluster-sample: # credential name
      auth-type: userpass
      password: a_password
      user: a_user
      vmfolder: a_folder